In [3]:
import numpy as np
from scipy.special import spence
import matplotlib.pyplot as plt

In [4]:
import os
os.getcwd()


'C:\\Users\\PENN\\Desktop\\reproducing_rad_corr'

In [4]:
os.listdir()



['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'documents',
 'LICENSE',
 'rad_corr_sanity_check.ipynb',
 'rad_corr_sanity_check_report.ipynb',
 'README.md',
 'table1_from_marc_paper.csv']

In [5]:
mp = .938272081
me = 0.5109989461 * 0.001
alpha = 1/137.036

## Loup's Note

In [3]:
qcm       = 0.458
# qcm_prime = 0.0625# 0.0875, 0.1125, 0.1375
Q2        = 0.2
E_e        = 0.9049#1.0024#1.0024
E_px       = 0
E_py       = 0
E_pz       = np.sqrt(E_e **2 - me**2)
Eprime_p       = 0.723#0.766#0.770#
Eprime_e       = np.sqrt(Eprime_p**2+me**2)
Eprime_theta   = np.radians(32.5)#np.radians(29.2)#np.radians(29.2)#
Pprime_p       = 0.462#0.486#0.411#
Pprime_e       = np.sqrt(Pprime_p**2 + mp**2)
Pprime_theta   = np.radians(52.2)#np.radians(51.0)#np.radians(42.5)#

Eprime_px = Eprime_p * np.sin(Eprime_theta)
Eprime_py = 0
Eprime_pz = Eprime_p * np.cos(Eprime_theta)

Pprime_px = -Pprime_p * np.sin(Pprime_theta)
Pprime_py = 0
Pprime_pz = Pprime_p * np.cos(Pprime_theta)

kdotpprime      = E_e * Pprime_e -  (E_px * Pprime_px + E_py * Pprime_py + E_pz * Pprime_pz)
kprimedotpprime = Eprime_e * Pprime_e -  (Eprime_px * Pprime_px + Eprime_py * Pprime_py + Eprime_pz * Pprime_pz)

deltaEs  = 0.025
Mm_2     = 2 * deltaEs

Eetilde      = mp/Mm_2 * (E_e       - Q2/2/mp - kdotpprime/mp)
Eeprimetilde = mp/Mm_2 * (Eprime_e  + Q2/2/mp - kprimedotpprime/mp)

sin_halfthetatilde_squared = E_e * Eprime_e / Eetilde/ Eeprimetilde * np.sin(Eprime_theta/2)**2

delta_vertex_reproduced = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)
delta_vac_reproduced    = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

deltaEs  = 0.025
Mm_2     = 2 * deltaEs

delta_r1_reproduced     = alpha/np.pi * np.log(deltaEs**2 /Eetilde/Eeprimetilde) * (np.log(Q2/me**2)-1)
delta_r2_reproduced = alpha/np.pi* (-0.5* (np.log(Eetilde/Eeprimetilde)**2) + 0.5 * np.log(Q2/me**2)**2 - np.pi**2/3 + spence(sin_halfthetatilde_squared))

rho = np.sqrt(Q2 + 4*mp**2)
aks = (np.sqrt(Q2) + rho)**2/4/mp**2
eta = 1 + E_e * (1 - np.cos(Eprime_theta))/mp
delta_1_reproduced   = 2*alpha/np.pi * (np.log(4*(deltaEs)**2/Q2/aks) * np.log(eta) + spence(1-(1-eta/aks)) - spence(1-(1-1/eta/aks)) ) # Scipy's spence(z) is Sp(1-z) in the convention Marc used.
delta_2_reproduced   = alpha/np.pi * ( np.log(4*(deltaEs)**2/mp**2)*(Eprime_p/Pprime_p*np.log(aks)-1) + 1 
                        + Eprime_p/Pprime_p * (-0.5*np.log(aks)**2 - np.log(aks)*np.log(rho**2/mp**2) + np.log(aks)
                        - spence( 1 - (1-1/aks/aks)) +2*spence( 1 - (-1/aks)) + np.pi**2/6 ) ) 

oneoverF_reporduced = 1 + delta_vac_reproduced + delta_vertex_reproduced + delta_r1_reproduced + delta_r2_reproduced + delta_1_reproduced + delta_2_reproduced
oneoverF_reproduced2 = np.exp(delta_vertex_reproduced + delta_r1_reproduced + delta_r2_reproduced)/ (1- 0.5 * (delta_vac_reproduced + delta_1_reproduced + delta_2_reproduced) )**2

delta_vac_reported    = 0.021
delta_vertex_reported = -0.168
delta_r1_reported     = -0.207
delta_r2_reported     = 0.210
delta_1_reported      = -0.0039907
delta_2_reported      = -0.0018
oneoverF_reported              = 0.855



print("\t\tL. Correa's report\t Sangbaek's Reproduction")
print("delta_vac \t {:.3e}\t\t {:.3e}".format(delta_vac_reported, delta_vac_reproduced))
print("delta_vertex \t {:.3e}\t\t {:.3e}".format(delta_vertex_reported, delta_vertex_reproduced))
print("delta_r1 \t {:.3e}\t\t {:.3e}".format(delta_r1_reported, delta_r1_reproduced))
print("delta_r2 \t {:.3e}\t\t {:.3e}".format(delta_r2_reported, delta_r2_reproduced))
print("delta_1 \t {:.3e}\t\t {:.3e}".format(delta_1_reported, delta_1_reproduced))
print("delta_2 \t {:.3e}\t\t {:.3e}".format(delta_2_reported, delta_2_reproduced))
print("1/F  \t\t {:.3f} pm {:.3f}\t\t {:.3f} (Exponentiated), {:.3f} (Summed)".format(oneoverF_reported, 0.01, oneoverF_reproduced2, oneoverF_reporduced ))

		L. Correa's report	 Sangbaek's Reproduction
delta_vac 	 2.100e-02		 1.840e-02
delta_vertex 	 -1.680e-01		 -1.668e-01
delta_r1 	 -2.070e-01		 -2.216e-01
delta_r2 	 2.100e-01		 2.090e-01
delta_1 	 -3.991e-03		 -4.195e-03
delta_2 	 -1.800e-03		 4.014e-03
1/F  		 0.855 pm 0.010		 0.851 (Exponentiated), 0.839 (Summed)


## Reproducing Virtuals (Marc's elastic paper)

In [6]:
Ee, thetae, Q2, delta_vertex, delta_vac, delta_R, delta_1, delta_2, delta_tot, delta_EXP =  np.loadtxt("table1_from_marc_paper.csv").T

In [5]:
delta_vertex_reproduced = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)
delta_vac_reproduced    = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [6]:
#Sangbaek Version
Eetilde      = Ee
Eeprime_el   = E_e / ( 1 + E_e/ (mp * (1-np.cos(thetae) ) ) )
Eeprime      = Eeprime_el# + 0.01*Ee
Eeprimetilde = Eeprime
deltaEs      = 0.01*Ee
delta_r1 = alpha/np.pi * np.log(deltaEs**2 /Eetilde/Eeprimetilde) * (np.log(Q2/me**2)-1)

#delta_r2 = alpha/np.pi* (-0.5* (np.log(Eetilde/Eeprimetilde)**2) + 0.5 * np.log(Q2/me**2)**2 - np.pi**2/3 + spence(1 - cossquared_thetatetilde_half))

In [7]:
#Corrections to these terms based on equations A44-46,49)
Eeprime      = (mp*Ee - Q2/2) / mp
Eetilde      = Eeprime
Eeprime_el   = 0.01 * Ee + Eeprime
Eeprimetilde = Ee
eta          = Ee / Eeprime_el
deltaEs      = eta * (Eeprime_el - Eeprime)


delta_r1     = alpha/np.pi * np.log(deltaEs**2 /Eetilde/Eeprimetilde) * (np.log(Q2/me**2)-1)

delta_r2 = alpha/np.pi* (-0.5* (np.log(Eetilde/Eeprimetilde)**2) + 0.5 * np.log(Q2/me**2)**2 - np.pi**2/3 + spence(1 - np.cos(thetae/2)**2))

In [12]:
#Sangbaek Version
rho = np.sqrt(Q2 + 4*mp**2)
aks = (np.sqrt(Q2) + rho)**2/4/mp**2
#eta = 0.01
delta_1_reproduced   = 2*alpha/np.pi * (np.log(4*(deltaEs)**2/Q2/aks) * np.log(eta) + spence(1-(1-eta/aks)) - spence(1-(1-1/eta/aks)) ) 

delta_2_reproduced   = alpha/np.pi * ( np.log(4*(deltaEs)**2/mp**2)*(Eprime_p/pprime_p*np.log(aks)-1) + 1 
                        + Eprime_p/pprime_p * (-0.5*np.log(aks)**2 - np.log(aks)*np.log(rho**2/M**2) + np.log(aks)
                        - spence( 1 - (1-1/aks/aks)) +2*spence( 1 - (-1/aks)) + np.pi**2/6 ) ) #A76

NameError: name 'pprime_p' is not defined

In [8]:
#Penn Version
#Note: The input to all spence functions in Sangbaek Version read as Sp(1-input) where "input" is the input from the paper.
#Update: This input version seems to be correct
rho = np.sqrt(Q2 + 4*mp**2)
aks = (np.sqrt(Q2) + rho)**2/4/mp**2
#eta = 0.01
Eprime_N = mp + Ee - Eeprime
pprime_N = np.sqrt(Eprime_N ** 2 - mp ** 2)
delta_1_reproduced   = 2*alpha/np.pi * (np.log(4*(deltaEs)**2/Q2/aks) * np.log(eta) + spence(1-(1-(eta/aks))) - spence(1-(1 - 1/eta/aks)) ) 

delta_2_reproduced   = alpha/np.pi * ( np.log(4*(deltaEs)**2/mp**2)*(Eprime_N/pprime_N*np.log(aks)-1) + 1 
                        + Eprime_N/pprime_N * (-0.5*np.log(aks)**2 - np.log(aks)*np.log(rho**2/mp**2) + np.log(aks)
                        - spence( 1 - (1-1/aks/aks)) +2*spence(1-(-1/aks)) + np.pi**2/6 ) ) #A77

In [9]:
delta_1_reproduced

array([-0.00622763, -0.01174718, -0.00425202, -0.01028166, -0.01745184,
       -0.02586017, -0.00586547, -0.00989142, -0.01442121, -0.01947098,
       -0.02508581])

In [10]:
delta_1

array([-0.0067, -0.0123, -0.0046, -0.0107, -0.018 , -0.0265, -0.0062,
       -0.0103, -0.0149, -0.02  , -0.0257])

In [11]:
delta_1 / delta_1_reproduced

array([1.07585125, 1.04705963, 1.08183756, 1.04068766, 1.03140998,
       1.02474175, 1.05703322, 1.0413064 , 1.03320016, 1.0271696 ,
       1.02448347])

In [12]:
delta_2 / delta_2_reproduced

array([1.00789952, 1.01118822, 1.00487506, 0.99225491, 0.99583297,
       0.99454433, 1.00082393, 0.99984243, 0.99382747, 0.99257866,
       0.99353312])

In [ ]:
delta_r2 + delta_r1, delta_R

(array([-0.0174266 , -0.00207379,  0.05543917,  0.07065605,  0.07994859,
         0.0866225 ,  0.08157654,  0.09139447,  0.09854753,  0.1041798 ,
         0.10880836]),
 array([-0.0453, -0.0245, -0.026 ,  0.0018,  0.03  ,  0.0623, -0.0097,
         0.0092,  0.0284,  0.049 ,  0.0718]))

In [ ]:
spence(1-(1-eta/aks))

array([1.60703627, 1.61291304, 1.62102196, 1.62752193, 1.63100886,
       1.63324653, 1.62752193, 1.63100886, 1.63324653, 1.63482274,
       1.63600041])

## Case 1) Ruonan's thesis

In [ ]:
E_beam = 4.55974
Q2     = 0.332
# s      = 2 * mp * E_beam
W      = 1.232
s      = W**2

In [ ]:
nu = (s - mp**2 +Q2)/2/mp

In [ ]:
q_cm = Q2 + (s-Q2 -mp**2)**2/4/s

In [ ]:
qprime_cm = (s-mp**2)/2/W

In [ ]:
q_cm, qprime_cm

(0.34736930774942615, 0.2587132719220493)

In [ ]:
E_e = E_beam - nu

In [ ]:
E_beamx  = 0
E_beamy  = 0
E_beamz  = np.sqrt(E_beam **2 - me**2)

In [ ]:
E_py = 0
E_pz = E_e * (1 - 2*Q2/E_e/E_beam/4)
E_px = np.sqrt( E_e**2 - E_pz**2)
E_e  = np.sqrt(E_px**2 + E_py**2 + E_pz**2 + me**2)

In [ ]:
P_py = 0
P_pz = 0.863 * np.cos(np.radians(44.3887 + 11))
P_px = -0.863 * np.sin(np.radians(44.3887 + 11))
P_e  = np.sqrt(P_px**2 + P_py**2 + P_pz**2 + mp**2)

In [ ]:
qprime_py = 0
qprime_pz = 0.18017 * np.cos(np.radians(44.3887 + 246.04485))
qprime_px = -0.18017 * np.sin(np.radians(44.3887 + 246.04485))
qprime_e  = np.sqrt(qprime_px**2 + qprime_py**2 + qprime_pz**2)

In [ ]:
assert qprime_e + P_e + E_e - E_beam - mp < 0.001

In [ ]:
kdotqprime = E_beam * qprime_e - E_beamx * qprime_px - E_beamy * qprime_py - E_beamz * qprime_pz

In [ ]:
kprimedotqprime = E_e * qprime_e - E_px * qprime_px - E_py * qprime_py - E_pz * qprime_pz

In [ ]:
np.degrees(np.arccos(1 - 2*Q2/E_e/E_beam/4))

np.float64(7.6946700031425515)

In [ ]:
Eetilde      = mp/Mm2 * (E_beam  - Q2/2/mp - kdotqprime/mp)
Eeprimetilde = mp/Mm2 * (E_e     + Q2/2/mp - kprimedotqprime/mp)
deltaEs      = Mm2/2
sinsquared_thetatetilde_half = E_beam * E_e / Eetilde/Eeprimetilde

In [ ]:
Q2d = Q2
Ed  = E_beam
Esc = E_e
costel = 1 - Q2d/(2*Ed*Esc)   

In [ ]:
cossquared_thetatetilde_half = 1 - sinsquared_thetatetilde_half

In [ ]:
delta_r1 = alpha/np.pi * np.log(deltaEs**2 /Eetilde/Eeprimetilde) * (np.log(Q2/me**2)-1)

In [ ]:
delta_r2 = alpha/np.pi* (-0.5* (np.log(Eetilde/Eeprimetilde)**2) + 0.5 * np.log(Q2/me**2)**2 - np.pi**2/3 + spence(cossquared_thetatetilde_half))

In [ ]:
delta_r1, delta_r2

(np.float64(-0.7203541272750198), np.float64(0.008682782803088377))

In [ ]:
delta_vac = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [ ]:
delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)

In [ ]:
delta_r1 + delta_r2 + delta_vertex

np.float64(-0.5712246044707574)

In [ ]:
delta_r1 + delta_r2

np.float64(-0.389922885319835)

In [ ]:
delta_1 = 2*alpha / np.pi *( np.log(4*deltaEs**2/Q2/x) * np.log(eta) + spence(1-eta/x) - spence(1-1/eta/x))
delta_2 = alpha/np.pi * ( np.log(4*(deltaEs**2)/mp**2) * (P_e/0.863 * np.log(x)-1) + P_e/0.863 * ( -0.5*np.log(x)**2 - np.log(x) * np.log(rho**2/mp**2) + np.log(x) -spencer(1-1/x**2) + 2*spence(-1/x)

In [ ]:
rho = np.sqrt(Q2 + 4*mp**2)
Q   = np.sqrt(Q2)
x = ( Q + rho )**2 /4/mp**2
eta = E_beam/E_e

In [ ]:
delta_1

np.float64(-0.0014046523249894986)

In [ ]:
spence(-1/x)

np.float64(nan)

## Case 2) Marc's paper; Elastic

In [ ]:
E_beam   = 0.855
theta_e  = np.radians(52.18)
Q2       = 0.418
E_e      = Q2/E_beam/(4*np.sin(theta_e/2)**2)

In [ ]:
E_e

np.float64(0.631937941082835)

In [ ]:
E_e = E_beam / ( 1 + E_beam/ mp * (1-np.cos(theta_e) ) ) 

NameError: name 'E_beam' is not defined

In [ ]:
E_px     = E_e * np.sin(theta_e)
E_py     = 0
E_pz     = E_e * np.cos(theta_e)

In [ ]:
P_px     = -E_px
P_py     = 0
P_pz     = E_beam - E_pz
P_e      = np.sqrt(P_px**2 + P_py**2 + P_pz**2 + mp**2)

In [ ]:
print(E_beam + mp - E_e - P_e)

0.3514137803771835


In [ ]:
deltaEs = 0.01 * ( E_beam - E_e)

In [ ]:
sinsquared_thetatetilde_half = np.sin(theta_e/2)**2
cossquared_thetatetilde_half = 1 - sinsquared_thetatetilde_half

In [ ]:
delta_r1 = alpha/np.pi * np.log(deltaEs**2 /E_e/E_beam) * (np.log(Q2/me**2)-1)
delta_r2 = alpha/np.pi * (-0.5* (np.log(E_e/E_beam))**2 + 0.5 * np.log(Q2/me**2)**2 - np.pi**2/3 + spence(np.cos(theta_e/2)**2))

In [ ]:
delta_r1 + delta_r2

np.float64(-0.040554495337663726)

In [ ]:
delta_r2

np.float64(0.22816125521832967)

In [ ]:
delta_vac = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [ ]:
delta_vac

np.float64(0.01954164085768474)

In [ ]:
delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)

In [ ]:
delta_vertex

np.float64(-0.1880812926773972)

## Case 3 Loop's thesis

In [ ]:
Q2 = 0.356
me = 0.5109989461 * 0.001
alpha = 1/137.036
delta_vac = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [ ]:
Mm2 = np.sqrt(2)
kdotqprime = E_beam * qprime_e - E_beamx * qprime_px - E_beamy * qprime_py - E_beamz * qprime_pz
Eetilde      = mp/Mm2 * (E_beam  - Q2/2/mp - kdotqprime/mp)
Eeprimetilde = mp/Mm2 * (E_e     + Q2/2/mp - kprimedotqprime/mp)


NameError: name 'qprime_e' is not defined

In [ ]:
delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)

In [ ]:
delta_vertex

np.float64(-0.18334293851140032)

In [ ]:
deltaEs  = np.sqrt(2)/2
E_e      = .843
E_beam   = .528
theta_e  = np.radians(53.14)

delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)
delta_vac = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))
delta_r1 = alpha/np.pi * np.log(deltaEs**2 /E_e/E_beam) * (np.log(Q2/me**2)-1)
delta_r2 = alpha/np.pi * (-0.5* (np.log(E_e/E_beam))**2 + 0.5 * np.log(Q2/me**2) - np.pi**2/3 + spence(np.cos(theta_e/2)**2))

In [ ]:
delta_vertex + delta_vac

np.float64(-0.1640499178487795)

In [ ]:
delta_vac + delta_v

NameError: name 'delta_v' is not defined

# MAMI VCS kinematics (Helene's note)

In [59]:
mp = .938272081
me = 0.5109989461 * 0.001
alpha = 1./137.0359895
pi    = 3.141592653589793
alpi  = alpha/pi


E      = 0.843
Eprime = 0.528
thetae = np.radians(53.14)
Q2     = 0.356

In [60]:
delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)
delta_vac    = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [61]:
delta_vertex + delta_vac

np.float64(-0.16404993041864635)

In [23]:
Q2

0.356